version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=/app/packages/backend/data/cities.db
    volumes:
      - backend_data:/app/packages/backend/data
    working_dir: /app/packages/backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app/packages/frontend
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
