version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=/app/packages/backend/data/cities.db
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./packages/backend/src:/app/packages/backend/src
      - ./packages/shared/src:/app/packages/shared/src
      - backend_data:/app/packages/backend/data
    working_dir: /app/packages/backend
    command: sh -c "./scripts/init-db.sh"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=/api
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - ./packages/shared/src:/app/packages/shared/src
    working_dir: /app/packages/frontend
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
